### ISSUE TITLE
Swimming statictic on watch face

### ISSUE THREAD

**Issue by M11-128k** [kelnage/digital-simplicity#10]
Most of the existing watch faces ignoring swimmers, in a favor of runners and cyclists. Would be great to have option of weekly distance cowered displayed on upper of lower field. Thank. Gear watch face, but could be even better with that improvement.

**Comment by kelnage** [comment]
Thanks for your comment. Unfortunately this is not something that watch face designers have much control over - they are given access to the metrics that Garmin offer them.

This watch face isn’t really designed particularly for any sport - the distance measurement is in terms of any step motion. Sadly watch faces don’t have any way to reliably access activity data over a period of time, so this is not a feature that be easily added.
