### ISSUE TITLE
Bluetooth 

### ISSUE THREAD

**Issue by mikafletcher** [kelnage/digital-simplicity#11]
Hi, I have a simple question. What is the number just next to the Bluetooth symbol ?
Thanks

**Comment by kelnage** [comment]
Hi @mikafletcher - the number next to the bluetooth symbol is the count of notifications that are available on the the mobile device that is connected to your watch via bluetooth. Hope that makes sense!

**Comment by mikafletcher** [comment]
Thanks, is it possible to not have it ?

**Comment by kelnage** [comment]
Hi @mikafletcher - I have added the option to hide the notification count in the latest release (v1.4.0).
